name: SimpleOtu
version: 3.0.0
author: beito
api: ["1.0.0"]
main: ru.bk.beito3.simpleotu.MainClass

commands:
  otu:
    description: "Otu the player"
    usage: "/otu <player>"
    permission: otu.command.otu
  unotu:
    description: "Unotu the player"
    usage: "/unotu <player>"
    permission: otu.command.unotu
  runa:
    description: "Runa the player"
    usage: "/runa <player>"
    permission: otu.command.runa
  otup:
    description: "Set the pos of the jail"
    usage: "/otup [<x> <y> <z> [world]]"
    permission: otu.command.otup
  otulist:
    description: "Show the list of otu."
    usage: "/otulist [otu|runa] [page]"
    permission: otu.command.otulist
  otuser:
    description: "Search the otu or runa player"
    usage: "/otuser <player>"
    permission: otu.command.otuser
  otur:
    description: "Set reason of otu or runa"
    usage: "/otur <player> <reason>"
    permission: otu.command.otuser

permissions:
  otu:
    children:
      otu.command:
        children:
          otu.command.otu:
            default: op
          otu.command.unotu:
            default: op
          otu.command.runa:
            default: op
          otu.command.otup:
            default: op
          otu.command.otulist:
            default: op
          otu.command.otuser:
            default: op