#Use Circle CI 2.0! very faster!
version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    working_directory: ~/workspace

    environment:
      GRADLE_OPTS: -Xmx4G -Dorg.gradle.daemon=true -Dorg.gradle.paralle=true

    #build steps
    steps:
          #Checkotu to working_directory
          - checkout

          #Restore cache (if exists no changed cache)
          - restore_cache:
              key: nukkit-plugins-{{ .Branch }}-{{ checksum "build.gradle" }}

          - run:
              name: Give permission for running to gradlew
              command: chmod +x ./gradlew

          - run:
              name: Show version. And if not exists gradle-bin, download
              command: ./gradlew -v

          - run:
              name: Build
              command: ./gradlew build

          - run:
              name: Test
              command: ./gradlew --full-stacktrace check

          #Thanks from http://qiita.com/yone098@github/items/bba8a42de6b06e40983b
          - run:
              name: Show dirs and files (instead of tree command)
              command: pwd ../;find ../ | sort | sed '1d;s/^\.//;s/\/\([^/]*\)$/|--\1/;s/\/[^/|]*/|  /g'

          #Save artifacts(.jar, etc..)
          - store_artifacts:
              path: ./dist/
              destination: dist/

          #Save Cache
          - save_cache:
              #Todo: add build.gradle of Sit or SimpleOtu etc..
              key: nukkit-plugins-{{ .Branch }}-{{ checksum "build.gradle" }}
              paths:
                - "~/.gradle/4.0"
                - "~/.gradle/wrapper/dists/gradle-4.0-bin"
                - "~/.gradle/caches/modules-2"
                - "~/.gradle/buildOutputCleanup"
