version: 2
jobs:
  build:
    docker:
      # see https://hub.docker.com/_/java/
      - image: circleci/java:8

    working_directory: ~/workspace

    environment:
      GRADLE_OPTS: -Xmx4G -Dorg.gradle.daemon=true -Dorg.gradle.paralle=true

    steps:
          - checkout

          - restore_cache:
              key: nukkit-plugins-{{ .Branch }}-{{ checksum "build.gradle" }}

          - run:
              name: Give gradlew x permission
              command: chmod +x ./gradlew

          - run:
              name: Show version and download dependencies
              command: ./gradlew -v

          - run:
              name: Build
              command: ./gradlew build

          - run:
              name: Test
              command: ./gradlew --full-stacktrace check

          - store_artifacts:
              path: ./dist/
              destination: dist/

          - save_cache:
              key: nukkit-plugins-{{ .Branch }}-{{ checksum "build.gradle" }}
              paths:
                - "~/.gradle/4.0"
                - "~/.gradle/wrapper/dists/gradle-4.0-bin"
                - "~/.gradle/caches/modules-2"
                - "~/.gradle/buildOutputCleanup"
