version: 2
jobs:
  build:
    docker:
      # see https://hub.docker.com/_/java/
      - image: java:8

    environment:
      GRADLE_OPTS: -Xmx4G -Dorg.gradle.daemon=true -Dorg.gradle.paralle=true

    branches:
      only:
        - master
        - circleci-test

    working_directory: ~/workspace

    steps:
          - checkout

          - restore_cache:
              key: nukkit-plugins-{{ .Branch }}-{{ checksum "build.gradle" }}

          - run:
            name: gradlewに実行権限を与える
            command: chmod +x ./gradlew

          - run:
            name: バージョン表示と依存関係のダウンロード
            command: ./gradlew -v

          - run:
            name: Build
            command: ./gradlew build

          - run:
            name: Test
            command: ./gradlew --full-stacktrace check

          - store_artifacts:
            path: ./dist/
            destination: dist/

          - save_cache:
              key: projectname-{{ .Branch }}-{{ checksum "build.gradle" }}
              paths:
                - "~/.gradle/4.0"
                - "~/.gradle/buildOutputCleanup"
                - "~/.gradle/wrapper/dists/gradle-4.0-bin"
                - "~/.gradle/caches/modules-2"
                - "~/.m2"

